### ISSUE TITLE
sketch crash...

### ISSUE THREAD

**Issue by TChengZ** [romannurik/Sketch-Stickers#1]
when i use it, sketch scrash...
the log in console is
`
Ignoring autorelease call on {
    emit = "<MOJavaScriptObject: 0x60800c433cc0>";
}
`

**Comment by romannurik** [comment]
Which version of Sketch and which version of macOS are you on?

**Comment by romannurik** [comment]
Hi there any update? My guess is this is related to an old version of either Sketch or macOS

**Comment by TChengZ** [comment]
sketch 50.2  macos 10.13.4

**Comment by romannurik** [comment]
I'm on the same setup, hmm. Do you have any Sketch libraries installed? Can you disable them all and try again?

**Comment by TChengZ** [comment]
i disabled all my libraries... and it work well...not any crash, thanks

**Comment by romannurik** [comment]
Oh hmm... could you try turning on your libraries one by one and seeing which one causes Stickers to crash? I'd love to be able to test what could be going on with that library that's causing the crash (so if you could even share the library file with me, that'd be amazing!)

**Comment by TChengZ** [comment]
have you update the plugin, i enabled all the libraries but the crash did not happen, also the sketch just show "None of your sketch libraries have stickers yet"
the log show like below
Ignoring autorelease call on {
    emit = "<MOJavaScriptObject: 0x600000624640>";
    emitBrowserEvent = "<MOJavaScriptObject: 0x600000622ec0>";
    parseWebArguments = "<MOJavaScriptObject: 0x60000043e140>";
    setTitle = "<MOJavaScriptObject: 0x600000637700>";
}

**Comment by romannurik** [comment]
There was a plugin update that could've fixed it, not sure. And yes now that you see nothing indexed, you can go ahead and follow the example library file to create stickers :-)
