### ISSUE TITLE
Bug: Missing symbols when including a linked symbol in a sticker

### ISSUE THREAD

**Issue by gavinanthony** [romannurik/Sketch-Stickers#11]
I have a fairly simple sticker document currently. Four different sized artboard templates. Each one has a different header symbol that's being pulled from another linked library.

As I drag that artboard into a blank sketch document, the symbol doesn't appear. Instead, it shows a red background with the missing symbol icon.
![image](https://user-images.githubusercontent.com/392797/43790097-41479b20-9a37-11e8-9ae8-a2dc81f940bd.png) 
Further more, I can no longer insert that symbol into that document.

Is this functionality supposed to be supported? Does this plugin require that symbols are local, not linked?

**Comment by romannurik** [comment]
Hey there! Could you share an example library that demonstrates the problem? I did a lot of work to fix issues like this but may have missed a case.

**Comment by gavinanthony** [comment]
I reproduced it with some basic symbols. You can see in the origin library, there is a color override being used as the background. This is the symbol that seems to be missing when it is included in the stickersheet.

Thanks for taking a look at this!

**Comment by romannurik** [comment]
Ah got it, just repro'd. Just found the problem too and fixed!
