### ISSUE TITLE
Existing Symbols break when importing them from Stickers

### ISSUE THREAD

**Issue by florianschulte** [romannurik/Sketch-Stickers#12]
Whenever I drag and drop a symbol into the files it breaks already existing symbols, for example, the bell Icon. Before inserting it from Stickers it worked all fine but broke after inserting it as an instance from a Sticker from Stickers, which broke the color override everywhere in the whole file for that symbol. (I've sent you the files privately)

**Comment by romannurik** [comment]
Thanks for filing this! I'm hoping to have some time to troubleshoot soon. I hope you're not too blocked on this bug!

**Comment by romannurik** [comment]
OK, definitely repro'd the issue with your sample files sent privately... will do some digging into what could be causing this.

**Comment by romannurik** [comment]
Found the issue, and am going to push a workaround soon... basically it will no longer break so long as you have the other library enabled in Sketch. If you drag+drop, and then *later* add the nested library and try to drag in the symbol, it'll still be broken. I still need to figure out the right way to handle that.

For posterity, calling `addForeignSymbol` on an `MSForeignSymbol` from another document is a little dangerous, and it looks like child symbols also will need to be added, or something like that. Added a TODO for myself to resolve.

**Comment by romannurik** [comment]
Should work for you as of v0.3.1

**Comment by iamhenry** [comment]
Thank you Roman for putting in the work for this amazing plugin.
