### ISSUE TITLE
[macOS Mojave] Unable to drag component in sketch 52.2

### ISSUE THREAD

**Issue by adwindwitaufani** [romannurik/Sketch-Stickers#13]
Hi Roman,

I've using Stickers for my team, and we're already using Sketch 52.2. We're facing a big problem cuz we're unable to drag the components from sticker to the artboard. 

Thanks

**Comment by romannurik** [comment]
Are you on macOS Mojave? I've heard it's broken there but don't have Mojave yet to test on :-/

**Comment by adwindwitaufani** [comment]
@romannurik Yep, I'm using Mojave. Ah I see, It's really helpful if you try using Mojave soon :D

**Comment by IlyaGrshin** [comment]
Hi there!

Any news on solving a problem? We had the same. :(

Thanks!

**Comment by romannurik** [comment]
Not yet, sorry... I'm trying to get my hands on a Mojave machine soon, but no luck yet.

**Comment by romannurik** [comment]
Anyone with Mojave, could you open the "Console" Mac app, and do a search for "Sketch", and then try drag + dropping? You should see some sort of error related to the Stickers plugin, hopefully you can paste it here :)

**Comment by IlyaGrshin** [comment]
Is DevTools suitable?

<img width="898" alt="2018-10-26 16 47 08" src="https://user-images.githubusercontent.com/36699605/47570442-de905200-d93e-11e8-94cb-72da7f909975.png">

**Comment by romannurik** [comment]
Yeah, anything that can show the error occurring during drag would help.

**Comment by romannurik** [comment]
Can you give this version a try? This is kind of a shot in the dark, though the change is really simple:
[Stickers.sketchplugin.zip](https://github.com/romannurik/Sketch-Stickers/files/2519824/Stickers.sketchplugin.zip)

**Comment by IlyaGrshin** [comment]
It didn't help. Errors are the same. :(

**Comment by romannurik** [comment]
Gah, ok. Will hopefully get access to Mojave soon.

**Comment by romannurik** [comment]
@IlyaGrshin any chance you could run that version of the plugin I shared and check the console for errors again?

**Comment by romannurik** [comment]
Fixed in v0.3.5!
