### ISSUE TITLE
Bug in sketch 53

### ISSUE THREAD

**Issue by tijmenvangurp** [romannurik/Sketch-Stickers#14]
doc.documentData().assets().colors is not a function. (In 'doc.documentData().assets().colors()', 'doc.documentData().assets().colors' is undefined)

**Comment by tijmenvangurp** [comment]
Some helpfull input here: 
https://sketchplugins.com/d/792-get-document-colors/7

**Comment by tijmenvangurp** [comment]
I think simply replacing
`const colors = doc.documentData().assets().colors();`
to
`const colors = doc.documentData().assets().colorAssets();` 
Solves it

See:
https://github.com/brainly/html-sketchapp/issues/154

**Comment by tijmenvangurp** [comment]
Nice! :)

**Comment by romannurik** [comment]
Just pushed the fix.

**Comment by romannurik** [comment]
Just pushed the fix.
