### ISSUE TITLE
Improvement: imported symbols should keep their style overrides if possible.

### ISSUE THREAD

**Issue by tijmenvangurp** [romannurik/Sketch-Stickers#15]
**Scenario:**
My document with symbol instances from the library has had changes to their style overrides.
e.g. the background from a button has changed to a different layer style (from the library).

When I drag in the symbol to the document it is reset to the layer style from the symbolMaster.

**Expected scenario:**
when dragging in a symbol I would expect that it creates an instance from the library and changes the overrides to the same styles as done in the library (if the style can be found in the library of course)

**My stickers file with changed style overrides**
![image](https://user-images.githubusercontent.com/9990026/52358623-a2d64f80-2a38-11e9-8e2a-10f4ba4abf81.png)

**Result**
![image](https://user-images.githubusercontent.com/9990026/52358652-b08bd500-2a38-11e9-905c-c57ddc41959f.png)

**Comment by tijmenvangurp** [comment]
The reason, why I want to be able to keep the style, overrides set like they where is because this way I can create multiple theming configurations as sticker sheets while having 1 single library to maintain all the styles.

**Comment by romannurik** [comment]
Hm, can you share your example sticker library .sketch file with me? (publicly or privately)

**Comment by tijmenvangurp** [comment]
Hey @romannurik ,
Sorry, it took me a while to prepare the files. 

[sketch-sample-files.zip](https://github.com/romannurik/Sketch-Stickers/files/2901211/sketch-sample-files.zip)

Not sure how to implement this though.
guessing a bit here:
On the symbol instance, save the symbol override values, and after importing the symbol master apply these override values on the imported symbol. 

Feel free to comment me on a Pull request if you have something.

**Comment by romannurik** [comment]
Hey there! I was helping another person over Twitter with something similar, can you test this version to see if it helps:

https://www.dropbox.com/s/bsnqu2uqeopr1df/Stickers-test.sketchplugin.zip?dl=0

**Comment by tijmenvangurp** [comment]
Hey @romannurik seems to work perfectly! 👍 Appreciate the quick response!

**Comment by romannurik** [comment]
Awesome!
