### ISSUE TITLE
Symbols from nested libraries not importing properly

### ISSUE THREAD

**Issue by tijmenvangurp** [romannurik/Sketch-Stickers#16]
![image](https://user-images.githubusercontent.com/9990026/53349708-fd6b1900-391d-11e9-9b27-f2785e6a8749.png)

The imported symbols are not linked correctly to the library via the stickers plugin. Which means any library update is not coming through properly.

To reproduce this please check the attached files in this issue:
https://github.com/romannurik/Sketch-Stickers/issues/15

I checked the code from the API that seems to work:
https://developer.sketchapp.com/reference/api/#importable-object

```
var symbolReferences = theStickerInstanceAsociatedLibrary.getImportableSymbolReferencesForDocument(theCurrentlyActiveDocument)
```

I am not sure how you would match a reference to a symbol instance without importing the reference first. maybe on the name?

Anyway, hope you are able to fix this bug! :)

**Comment by romannurik** [comment]
This looks like a symbol from a nested library (two separate .sketch files) ... will look into iit.

**Comment by romannurik** [comment]
I think I'll have a fix for this. The link I shared in #15 has a test build.
