### ISSUE TITLE
import symbol as foreign symbols?

### ISSUE THREAD

**Issue by funfungo** [romannurik/Sketch-Stickers#20]
when i use sticker to import my library symbols, I found it import symbols as group.
I think the better practice would be the same as importing components using sketch library. 
when the library update, each file using the components can get a notification. so pls consider this issue.

**Comment by romannurik** [comment]
Hi there, the plugin lets you create stickers that are simple layers/groups, as well as stickers that are actually instances of symbols that are defined in the library. So if you want all the benefits of libraries+symbols, just add an instance of a symbol to your library file and tag it as a sticker. Check out the example file for an example.
