### ISSUE TITLE
Breaks in Sketch 66

### ISSUE THREAD

**Issue by txcrew** [romannurik/Sketch-Stickers#27]
Just upgraded to Sketch 66 and it seems like Stickers hangs at `indexing libraries` stage and won't launch.

Downgrading to Sketch 65.1 resolves the issue for the time being.

**Comment by romannurik** [comment]
Thanks for filing! Will take a look ASAP. Have a few compatibility issues to look at across some of my plugins.

**Comment by romannurik** [comment]
Should be fixed in 0.3.10

**Comment by txcrew** [comment]
Thank you for the super quick fix!
