### ISSUE TITLE
Search issues in Sketch 65.1

### ISSUE THREAD

**Issue by txcrew** [romannurik/Sketch-Stickers#28]
The search functionality works inconsistently in Sketch 65.1. The "type-ahead" search feature seems to only filter the stickers by the first two characters of the search query.

### Steps to reproduce
1. Launch Sketch 65.1
2. Start a new file
3. Stickers plugin -> `clear library index`
4. Show stickers 
5. Search for a sticker and place in your canvas.
6. Launch stickers plugin
7. Search for another sticker

This is the point the issue occurs; the search queries made after the initial search. Only the first two characters get searched, and then nothing else.

**Comment by romannurik** [comment]
Thanks for the detailed report! I'll see if I can repro next chance I have. It might be useful to share the library you're working with in case it's a situational bug

**Comment by txcrew** [comment]
Ah! You're right. My apologies for the premature report, it was a situational bug. I tested with a few other libraries, and it works correctly.

I'll dig into the meta tags a bit deeper and figure out where the problem is. 

Thanks for the quick response!

**Comment by romannurik** [comment]
OK, please do comment with details if you know what causes the bug!

**Comment by txcrew** [comment]
Resolved!

Kind of a needle in the haystack with all of the stickers we have in our libraries, but somehow a designer managed to name a couple like this:
```
Title + Body + Primary Button @notifications.banner @notifications.banner
```
instead of
```
Title + Body + Primary Button @notifications.banner
```

Removing the extraneous `@notificaitons.banner` in the layer name resolved the issue completely.

Not sure how it got there, but we'll chalk it up to several different hands managing libraries.
