### ISSUE TITLE
Link to install library from Sketch Cloud

### ISSUE THREAD

**Issue by bomberstudios** [romannurik/Sketch-Stickers#5]
It would be nice to upload the sample library to Sketch Cloud, and then you could have a link on the README / Wiki to install it into Sketch.

The URL format for that is `https://sketch.cloud/add-library/shareID`, so for example our Mac Library (that lives at https://sketch.cloud/s/VEp78) can be installed by clicking this link <a href="https://sketch.cloud/add-library/VEp78">https://sketch.cloud/add-library/VEp78</a>.

Hope it helps!

**Comment by romannurik** [comment]
Excellent idea! Will look into this today :-)

**Comment by romannurik** [comment]
Ah I just realized it's tricky for me since we don't have access to Sketch Cloud (probably related to site license v. personal license). Will keep digging into it.

**Comment by bomberstudios** [comment]
Contact me privately at ale@sketchapp.com with details about your license and I’ll see what’s going on

**Comment by romannurik** [comment]
Will do!

**Comment by romannurik** [comment]
Done! Added to the [wiki page on getting started for authors](https://github.com/romannurik/Sketch-Stickers/wiki/Getting-started-for-stickersheet-authors)
