### ISSUE TITLE
Maintain Link to original symbol from library

### ISSUE THREAD

**Issue by tijmenvangurp** [romannurik/Sketch-Stickers#6]
I have a sticker sheet making use of external libraries. 

That sticker sheet I add as a library so that it gets indexed by the sticker plugin (as per instructions)

But any symbol then placed via the plugin is linked to the stickers library not its original library. I guess it was not meant for the setup that I have, but could it be possible that symbols stay linked to their original library?

I was browsing a bit through the code and found this TODO:

// TODO: for symbols in a library that's nested within the given library, import from
// that library instead of the given library

👍  I need this!

**Comment by romannurik** [comment]
Hey there, yes, I have a TODO in the code related to this. Will hopefully look into it soon. I recall it being nontrivial but certainly a better behavior.

**Comment by romannurik** [comment]
One question related to this, is what to do if the nested library isn't added to your Libraries. This is what Sketch shows now:

**Comment by tijmenvangurp** [comment]
Hmm, there is no way of circumfenting this? I mean if I would copy paste the symbol instance from my stickersheet to another file while not having the related library included it would still work. If I would afterwards include the library the linking would still work. So the question is could you copy the symbol instance instead of trying to get the master of the linked library?

**Comment by romannurik** [comment]
OK I think I have a very clean fix for this, will probably need some more testing though.

**Comment by romannurik** [comment]
Fix is in v0.2.0

**Comment by tijmenvangurp** [comment]
In the latest v.0.2.0 it stays stuck on progress loading. No errors in the console.  I restarted sketch several times, and removed any libraries with @sticker.tags 

![image](https://user-images.githubusercontent.com/9990026/41215663-b732c480-6d51-11e8-94b8-3699a427f160.png)

**Comment by romannurik** [comment]
Looks like something went wrong with the upgrade process.. try deleting `~/Library/Caches/net.nurik.roman.sketch.stickers` I'll try to get a fix out today. Also an uninstall and reinstall of the plugin may help?

**Comment by romannurik** [comment]
Try v0.2.1... may need to restart Sketch. (I need to figure out how to avoid needing a restart still)
